### ISSUE TITLE
Error: Unsupported operand types in /[...]/probe/src/Controller/ProbeController.php on line 352

### ISSUE THREAD

**Issue by ideb** [ezcompany/probe#5]

**Comment by paulvandenburg** [comment]
@ideb could you explain the steps to reproduce the issue?
I don't have the mentioned error locally.

**Comment by ideb** [comment]
Steps to reproduce:
- Enable a module where `unserialize($module->serialize()` return false. Locally this occurred with the Admin toolbar module. 

![probe-unsupported-operand-types](https://user-images.githubusercontent.com/200380/52276313-279a6e00-2952-11e9-8feb-d42dc74d6532.png)

**Comment by paulvandenburg** [comment]
I already had the admin_toolbar installed locally, yet I still couldn't reproduce the issue.
However I've looked into why the serialize/unserialize was added in the first place and I see no reason why that is necessary.
So I guess that is sufficient reason to accept the PR.
